### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by jvn1567**
Unsure about the last two problems. I used the livescript this time so if you download the zip it'll open right in your browser.

### CODE REVIEW

**Comment by jvn1567** [comment]
@Tonyk0901

**Comment by Tonyk0901** [comment]
Sorry for being late.

Logic wise, everything makes sense. 
Format wise, it would be better if you include the plot of 10k pixel probability distribution in problem 3 part (b).

Also, in the our class slack channel(https://app.slack.com/client/TNURK4KUJ/CP7K6R9GV), there is this important comment from grading TA. Seems like you haven't seen it yet, so I will copy here.

Hi @everyone, this came up a lot when I was grading lab 1, so I thought I'd just put this here as a general message:
Plots are an important tool for communicating scientific research; plots are often the big 'takeaway' for research and a lot of work goes into them. So, I have a few tips:
1. Plots should be as self-contained as possible. This means including labels with axes (with units if appropriate) and a title as a bare minimum. If multiple quantities are being plotted at once, a legend should be included to distinguish them. In some cases, a text box that contains pertinent details is helpful (such as some important statistic relating to the distribution being plotted).
2. Plots should have a purpose. If you make a plot, make sure you have a clear motivation for that plot; don't just include it because you feel that it's been too many sentences since you last plotted anything.
3. Multiple distributions can be in a single plot. In the recent lab, parts where you were asked to vary parameters of a model are a great use-case for this. If you're trying to see the difference between multiple quantities, having them on the same plot is a great place to start.
4. Subplots exist. If plotting multiple quantities on the same plot is not feasible, but the quantities are still clearly related, you can plot them next to each other using subplots.
5. Don't go overboard with the above two points. Some people go crazy and plot 25 different distributions on the same plot, or split their plot up into 16 subplots. If it starts becoming difficult to read, tone it down a bit. Appealing to point 3, plots should have a single purpose; don't muddy your message with information that is not critical.

**Comment by jvn1567** [comment]
@Tonyk0901  I only see your lab 2 from the end of lab

**Comment by sfzhu** [comment]
1.A) mu = 7, then the range [0, 10] won't be enough. also, your parameters for the normal distribution is wrong, x range for yd3, yd5, they should all start from 0, check the code below.

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
mu = 7
x = np.arange(0, 21)
y = stats.poisson.pmf(x, mu)
y = y/np.sum(y)

x1 = x
y1 = y

x2 = np.arange(0, 2*x[-1] + 1)
y2 = np.convolve(y1, y)

x3 = np.arange(0, 3*x[-1] + 1)
y3 = np.convolve(y2, y)

x4 = np.arange(0, 4*x[-1] + 1)
y4 = np.convolve(y3, y)

x5 = np.arange(0, 5*x[-1] + 1)
y5 = np.convolve(y4, y)

y5_n = stats.norm.pdf(x5, loc=(5mu), scale=np.sqrt(5mu))
y5_n = y5_n/np.sum(y5_n)

plt.plot(x1, y1, label='1')
plt.plot(x3, y3, label='3')
plt.plot(x5, y5, label='5')
plt.plot(x5, y5_n, label='5 normal')
plt.legend()
plt.show()

Problem 2.
The same problem as the first one.

**Pull request merged**
