### PR TITLE
Lab4

### PR DESCRIPTION
**Pull request by jvn1567**
Not entirely sure how to approach the last part of problem 1 about 5 sigma.

Also I could not download the data from the other set for problem 2 using similar code as for the previous set. I was wondering if you had any luck?

### CODE REVIEW

**Comment by jvn1567** [comment]
@Tonyk0901 just figured out what I did wrong, working on problem 2 now

**Comment by Tonyk0901** [comment]
Sorry, but can you also put up the updated HTML file? Cuz it seems Github does not render live script file and I don't have Matlab, so I can only look at your code through HTML.

**Comment by Tonyk0901** [comment]
@jvn1567 
Things look good. Just one thing. Number 2-(3) is not showing in the HTML.

**Comment by jvn1567** [comment]
@sfzhu

**Comment by sfzhu** [comment]
I think now you may have a better understanding of what's going on. Let me know if you still have any questions.

**Pull request merged**
